### ISSUE TITLE
After adding functions, email will not confirm for authentication

### ISSUE THREAD

**Issue by christopher-kapic** [stripe-samples/netlify-stripe-subscriptions#7]
# Bug report

Before I began to add functions in `/functions/`, everything was working. Then, in the commit after I added `/functions/`, when I tried to sign up as a new user the email failed to confirm.

## Describe the bug

I get this error message:
![image](https://user-images.githubusercontent.com/59740769/109672117-520f8300-7b3a-11eb-9974-25811a26a24e.png)

## System information

-SSG: 11ty

**Comment by beatsbybre** [comment]
Same - also on reviewing console log 

Failed to load resource: the server responded with a status of 402 () /.netlify/functions/get-protected-content:1

{"errorType":"SyntaxError","errorMessage":"Unexpected end of JSON input","trace":["SyntaxError: Unexpected end of JSON input","    at JSON.parse (<anonymous>)","    at Runtime.exports.handler (/var/task/src/get-protected-content.js:34:25)","    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"]}

**Comment by jlengstorf** [comment]
hi, @christopher-kapic — this notification slipped past me, so I'm just now seeing this. are you still having this issue? it appears to be something with the Netlify Identity Widget and not with this example specifically, but I'm happy to try and dig in if you still need help. I'm going to preemptively close, but I'll open this again if you still need help

**Comment by christopher-kapic** [comment]
Hey @jlengstorf,
I am no longer having this issue, but just so you know--it happens when the `identity-signup` function throws an error.

Also, thank you for your Netlify and Stripe subscription tutorial. It is super helpful!

**Comment by jlengstorf** [comment]
thank you for the additional context! I appreciate it!
